wskey:  UGmcRN8FVQh7JIgMeBuBOpX76PWmhuwAk9QI5x9GmZLiXiq2AcODqeCqoEX0WIZLaTJVJlPYPK1Q2k3i
secret: NCM4CTpff30TXD8qAYfYZoxijJ/kbqRW
principalID: 320bda9a-0287-4935-bc12-9fc147327519
principalIDNS: urn:oclc:platform:86619
institution: 866191